services:
  lockss:
    image: lockss/lockss-daemon
    container_name: lockss
    hostname: localhost
    user: "lockss:${UID}:${GID}"
    env_file: lockss.env
    ports:
      - "9729:9729" # LCAP v3
      - "8081:8081" # LOCKSS Web Admin UI
    volumes:
      - type: bind
        source: /etc/lockss/config.dat
        target: /etc/lockss/config.dat
      - /lockss:/lockss
      - /var/log/lockss:/var/log/lockss
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss -n --listening --tcp | grep -P 'LISTEN.+:9729' || exit 1"
      timeout: 3s
      retries: 0
