services:
  postgres:
    image: postgres:14
    container_name: lockss-pgsql
    env_file: .env
    environment:
      POSTGRES_USER: LOCKSS
      POSTGRES_DB: LOCKSS
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U LOCKSS"]
      interval: 10s
      timeout: 5s
      retries: 5

  lockss:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
      platforms:
        - linux/amd64
    image: lockss/lockss-daemon
    platform: linux/amd64
    container_name: lockss
    hostname: localhost
    env_file: .env
    ports:
      - "9729:9729" # LCAP v3
      - "8081:8081" # LOCKSS Web Admin UI
    volumes:
      - type: bind
        source: ${LOCKSS_CONFIG_FILE}
        target: /etc/lockss/config.dat
      - ${LOCKSS_KEYS_DIR}:/etc/lockss/keys
      - ${LOCKSS_DATA_DIR}:/lockss
      - ${LOCKSS_LOG_DIR}:/var/log/lockss
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss -n --listening --tcp | grep -P 'LISTEN.+:9729' || exit 1"
      timeout: 3s
      retries: 0

volumes:
  postgres-data:
