services:
  lockss:
    image: lockss/lockss-daemon
    container_name: lockss
    hostname: localhost
    env_file: lockss.env
    ports:
      - "9729:9729" # LCAP v3
      - "8081:8081" # LOCKSS Web Admin UI
    volumes:
      - /etc/lockss/config.dat:/etc/lockss/config.dat
      - /lockss:/lockss
      - /var/log/lockss:/var/log/lockss
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss -n --listening --tcp | grep -P 'LISTEN.+:9729' || exit 1"
      timeout: 3s
      retries: 0
